# fly.toml app configuration file generated for audium-backend on 2024-11-06T17:49:25+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'audium-backend'
primary_region = 'sin'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[http_service]
  internal_port = 7070
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
